---
- hosts: pro
  remote_user: ubuntu
  gather_facts: no
  become: yes
  become_method: sudo
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
    - name: install nodejs
      apt:
        name: nodejs
        state: latest
        update_cache: yes
      ignore_errors: True