---
- hosts: localhost
  remote_user: ubuntu
  gather_facts: no
  become: yes
  become_method: sudo
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
    - name: Create a new directory
      file:
        path: pro
        state: directory
    - name: Pull project/media from git
      git:
        repo: 'https://github.com/APTXCassieZhu/pro'
        dest: pro
    - name: install nodejs
      apt:
        name: nodejs
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: install npm
      apt: 
        name: npm
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: Update packages based on package.json to their latest version.
      npm:
        path: /app/location
        state: latest
    - name: make Oracle JRE package available
      apt_repository:
        repo: ppa:webupd8team/java
    - name: update 
      apt:
        update_cache: yes
    - name: install java for cassandra
      apt:
        name: openjdk-8-jdk
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: add the key for the cassandra debian repo
      apt_key: 
        keyserver: keyserver.ubuntu.com 
        id: F758CE318D77295D
    - name: add the other key for cassandra
      apt_key: 
        keyserver: keyserver.ubuntu.com 
        id: A278B781FE4B2BDA
    - name: add cassandra debian repository
      apt_repository: 
        repo: 'deb http://www.apache.org/dist/cassandra/debian 311x main' 
        state: present
    - name: install cassandra
      apt:
        name: cassandra
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: make sure cassandra running
      service:
        name: cassandra
        state: restarted
    - name: replace old version cassandra conf
      copy:
        src: pro/cassandra.yaml
        dest: /etc/cassandra/cassandra.yaml
    - name: npm install cassandra driver
      npm:
        name: cassandra-driver
        path: /app/location
        state: latest
