---
- hosts: localhost
  remote_user: ubuntu
  gather_facts: no
  become: yes
  become_method: sudo
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
    - name: Create a new directory
      file:
        path: /pro
        state: directory
    - name: Pull project/media from git
      git:
        repo: 'https://github.com/APTXCassieZhu/pro'
        dest: /pro
    - name: install nodejs
      apt:
        name: nodejs
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: install npm
      apt: 
        name: npm
        state: latest
        update_cache: yes
      ignore_errors: True