---
- hosts: pro
  remote_user: ubuntu
  gather_facts: no
  become: yes
  become_method: sudo
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
    - name: install nodejs
      shell:
        sudo apt-get install nodejs
      ignore_errors: True