---
- hosts: localhost
  remote_user: ubuntu
  gather_facts: no
  become: yes
  become_method: sudo
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
    - name: Create a new directory
      file:
        path: pro
        state: directory
    - name: Pull project/media from git
      git:
        repo: 'https://github.com/APTXCassieZhu/pro'
        dest: pro
    - name: install nodejs
      apt:
        name: nodejs
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: install npm
      apt: 
        name: npm
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: install jave for cassandra
      apt:
        name: oracle-java8-set-default
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: install cassandra
      apt:
        name: cassandra
        state: latest
        update_cache: yes
      ignore_errors: True
    - name: make sure cassandra enable
      service:
        name: cassandra
        state: enable
    - name: make sure cassandra running
      service:
        name: cassandra
        state: restart